// 把 lol-html 的 .wasm 转成 base64 ES 模块，让 esbuild 能把它内联进单文件产物。
//
// 为什么要这么做：EdgeOne Edge Functions 只接受一个 JS 文件，没有 `import x from "*.wasm"`
// 这种打包器魔法，也没有文件系统可以 readFileSync。base64 内联是唯一能把 WASM
// 送上边缘节点的途径。
//
// 产物是生成物，不进 git（见 .gitignore），每次 build 前自动重跑。
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);
const pkgEntry = require.resolve("htmlrewriter/package.json");
const wasmPath = join(dirname(pkgEntry), "dist", "html_rewriter_bg.wasm");

const bytes = await readFile(wasmPath);
const b64 = bytes.toString("base64");

const outDir = new URL("../src/generated/", import.meta.url);
await mkdir(outDir, { recursive: true });
await writeFile(
  new URL("wasm-b64.js", outDir),
  `// AUTO-GENERATED by scripts/gen-wasm.mjs — do not edit, do not commit.\n` +
    `// source: htmlrewriter/dist/html_rewriter_bg.wasm (${bytes.length} bytes)\n` +
    `export default "${b64}";\n`
);

console.log(
  `[gen-wasm] ${wasmPath}\n` +
    `[gen-wasm] ${bytes.length} B wasm -> ${b64.length} B base64 -> src/generated/wasm-b64.js`
);
